- components/WhiteList/WhiteList.tsx
- pages/claim-tokens.tsx
- pages/index.tsx
- pages/pools/[address]/index.tsx
- pages/pools/create.tsx
- pages/pools/index.tsx
- pages/stake.tsx
This small PR adds title to all pages.
Now:
Before:
> Add title to all pages

- constants/token.ts
- pages/pools/index.tsx
- sections/AelinPool/FilterPool.tsx
Also set aelingov.eth as default sponsor filter value.
> Clear filters by clicking on View All Pool button

- pages/pools/index.tsx
- queries/pools/usePoolBalancesQuery.ts
- sections/AelinDeal/VestingDeal.tsx
- sections/AelinPool/PurchasePool.tsx
- sections/AelinPool/ViewPool.tsx
It includes the fixes for:
- Decimals are not showing properly on the current pools (Some contract requests fails)
- Cap Reached is displayed when the pool is created as uncapped
- Confirm popup doesn't close when vesting a deal after the tx is submitted 
- Sponsor Fee is too large on the homepage list
> Fix UI issues

- sections/Header/Header.tsx
> add uniswap link (#151)

- components/ActionBox/ActionBox.tsx
- components/Grid/Grid.tsx
- components/QuestionMark/QuestionMark.tsx
- pages/stake.tsx
Hi,
This PR includes:
- Buttons to Accept or Reject deals
- Wording changes on Stake page.
> Add some ui changes

- components/ActionBox/ActionBox.tsx
- components/Grid/Grid.tsx
- components/QuestionMark/QuestionMark.tsx
- pages/stake.tsx
* Change stake page wording
* Use buttons to Accept or Reject deals
* Add some tweaks
* Use theme colors
* minor updates
> Add some ui changes (#153)

- components/ActionBox/ActionBox.tsx
- components/common.tsx
- constants/pool.ts
* Change stake page wording
* Use buttons to Accept or Reject deals
* Add some tweaks
* Use theme colors
* Disable Purchase button for some pools
Co-authored-by: Aelin-xyz <89638770+Aelin-xyz@users.noreply.github.com>
Co-authored-by: 0xcdb <90234851+0xcdb@users.noreply.github.com>
> Disable the Purchase button for some pools (#155)

- sections/AelinDeal/AcceptOrRejectDeal.tsx
- sections/AelinDeal/CreateDeal.tsx
- sections/AelinDeal/FundDeal.tsx
- sections/AelinPool/ViewPool.tsx
* Improve Exchange Rates
* comment addresed
* Use every instead of some function
* fix order
> Improve Exchange Rates (#157)

- components/ActionBox/ActionBox.tsx
- constants/pool.ts
> release the seldon pool (#159)

- containers/ContractsInterface/contracts/AelinPoolFactory.ts
- sections/AelinDeal/AcceptOrRejectDeal.tsx
> prepare for aelip-7 updates (#164)

- sections/AelinDeal/WithdrawExpiry.tsx
- sections/AelinPool/ViewPool.tsx
* holder can withdraw unredeemed tokens after deal expiration
* holder ability to withdraw unredeemed deal tokens is working. will continue testing and update as needed
> holder can withdraw unredeemed tokens after deal expiration (#163)

- pages/stake.tsx
This PR change the tutorial link on the Stake page
> Change the tutorial link on the Stake page

- hooks/useAddressesToSymbols.ts
- pages/pools/index.tsx
This PR adds the ability to filter by currency symbols.
Closes #185
> Add filter by currency symbol

- sections/Deals/CreateDeal.tsx
- sections/Deals/FundDeal.tsx
- sections/Pools/ViewPool.tsx
* cancel pool feature
* text updates
> cancel pool feature (#219)

- sections/Deals/AcceptOrReject/AcceptOrRejectSection/AcceptOrRejectSection.tsx
- sections/Pools/PoolDurationEnded/PoolDurationEndedSection/PoolDurationEndedSection.tsx
- sections/Pools/PurchasePool/PurchasePoolSection/PurchasePoolSection.tsx
> Clear input value after submitting a tx

- constants/routes.ts
- sections/Footer/Footer.tsx
- sections/Header/Header.tsx
> Move Docs to the right

- pages/stake.tsx
> udpate text on deal fees (#238)

- utils/validate/create-pool.ts
* Use 7 characters as limit for pool symbol
* fix error message
> Use 7 characters as limit for pool symbol (#244)

- components/Input/InputGroup.tsx
- sections/Stake/StakeBox/StakeBox.tsx
> added InputGroup

- components/Svg/Svg.tsx
- components/Svg/index.tsx
- components/Table/Pagination.tsx
- styles/theme/index.ts
> Added icons and changed colors in pagination component

- components/QuestionMark/QuestionMark.tsx
- components/Table/Table.tsx
- pages/pools/index.tsx
> improved table

- containers/UI/UI.tsx
- package-lock.json
- package.json
- pages/_app.tsx
- pages/_document.tsx
- styles/theme/index.ts
> Fix theme when refresing the site

- components/Svg/Svg.tsx
- components/Table/Table.tsx
- pages/pools/index.tsx
- styles/theme/colors.ts
> added sorting

- constants/networks.ts
- containers/AddressToEns/AddressToEns.tsx
- containers/AddressToEns/index.ts
- pages/_app.tsx
- pages/pools/[...poolData]/index.tsx
- pages/pools/index.tsx
- queries/pools/useGetPoolsQuery.ts
- sections/Pools/FilterPool.tsx
- utils/crypto.ts
* WIP - Reduce infura calls
* Reduce infura calls
* tidy up
Co-authored-by: saeta.eth <saeta@aelindao.xyz>
> Reduce infura calls (#342)

- pages/pools/[...poolData]/index.tsx
Co-authored-by: saeta.eth <saeta@aelindao.xyz>
> fix network modal (#344)

- package-lock.json
- sections/Deals/Vesting/VestingBox/AllVestedBox/AllVestedBox.tsx
- sections/Deals/Vesting/VestingBox/VestingDealBox.tsx
- sections/Deals/Vesting/VestingBox/VestingScheduleBox/VestingScheduleBox.tsx
- sections/Deals/Vesting/VestingDealSection/VestingSection.tsx
> Fixed claimedAmount calculation and formatUnits argument

- package-lock.json
- sections/Deals/Vesting/VestingBox/AllVestedBox/AllVestedBox.tsx
- sections/Deals/Vesting/VestingBox/VestingDealBox.tsx
- sections/Deals/Vesting/VestingBox/VestingScheduleBox/VestingScheduleBox.tsx
- sections/Deals/Vesting/VestingDealSection/VestingSection.tsx
* Fixed claimedAmount calculation and formatUnits argument
* tidy up
* fix types
* fix ci
* implmented suggestions
Co-authored-by: saeta.eth <saeta@aelindao.xyz>
> Fixed claimedAmount calculation and formatUnits argument (#348)

- sections/Deals/Vesting/VestingDealSection/VestingSection.tsx
- sections/Pools/ViewPool.tsx
* add my deal total on v1 dapp
* switch to use wei for precision and add to dependency array
> add my deal total on v1 dapp (#383)

- sections/Stake/StakeSection/StakeSection.tsx
- utils/network.ts
* add staking multiplier
* Add extra gas to stake txs
Co-authored-by: saeta.eth <saeta@aelindao.xyz>
> Stake gas (#385)
